//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttribute) DeepCopyInto(out *SearchAttribute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttribute.
func (in *SearchAttribute) DeepCopy() *SearchAttribute {
	if in == nil {
		return nil
	}
	out := new(SearchAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchAttribute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttributeList) DeepCopyInto(out *SearchAttributeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchAttribute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttributeList.
func (in *SearchAttributeList) DeepCopy() *SearchAttributeList {
	if in == nil {
		return nil
	}
	out := new(SearchAttributeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchAttributeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttributeObservation) DeepCopyInto(out *SearchAttributeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttributeObservation.
func (in *SearchAttributeObservation) DeepCopy() *SearchAttributeObservation {
	if in == nil {
		return nil
	}
	out := new(SearchAttributeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttributeParameters) DeepCopyInto(out *SearchAttributeParameters) {
	*out = *in
	if in.TemporalNamespaceName != nil {
		in, out := &in.TemporalNamespaceName, &out.TemporalNamespaceName
		*out = new(string)
		**out = **in
	}
	if in.TemporalNamespaceNameRef != nil {
		in, out := &in.TemporalNamespaceNameRef, &out.TemporalNamespaceNameRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.TemporalNamespaceNameSelector != nil {
		in, out := &in.TemporalNamespaceNameSelector, &out.TemporalNamespaceNameSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttributeParameters.
func (in *SearchAttributeParameters) DeepCopy() *SearchAttributeParameters {
	if in == nil {
		return nil
	}
	out := new(SearchAttributeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttributeSpec) DeepCopyInto(out *SearchAttributeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttributeSpec.
func (in *SearchAttributeSpec) DeepCopy() *SearchAttributeSpec {
	if in == nil {
		return nil
	}
	out := new(SearchAttributeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchAttributeStatus) DeepCopyInto(out *SearchAttributeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchAttributeStatus.
func (in *SearchAttributeStatus) DeepCopy() *SearchAttributeStatus {
	if in == nil {
		return nil
	}
	out := new(SearchAttributeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespace) DeepCopyInto(out *TemporalNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespace.
func (in *TemporalNamespace) DeepCopy() *TemporalNamespace {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespaceList) DeepCopyInto(out *TemporalNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TemporalNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespaceList.
func (in *TemporalNamespaceList) DeepCopy() *TemporalNamespaceList {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemporalNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespaceObservation) DeepCopyInto(out *TemporalNamespaceObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.OwnerEmail != nil {
		in, out := &in.OwnerEmail, &out.OwnerEmail
		*out = new(string)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.HistoryArchivalUri != nil {
		in, out := &in.HistoryArchivalUri, &out.HistoryArchivalUri
		*out = new(string)
		**out = **in
	}
	if in.VisibilityArchivalUri != nil {
		in, out := &in.VisibilityArchivalUri, &out.VisibilityArchivalUri
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespaceObservation.
func (in *TemporalNamespaceObservation) DeepCopy() *TemporalNamespaceObservation {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespaceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespaceParameters) DeepCopyInto(out *TemporalNamespaceParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.OwnerEmail != nil {
		in, out := &in.OwnerEmail, &out.OwnerEmail
		*out = new(string)
		**out = **in
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.HistoryArchivalUri != nil {
		in, out := &in.HistoryArchivalUri, &out.HistoryArchivalUri
		*out = new(string)
		**out = **in
	}
	if in.VisibilityArchivalUri != nil {
		in, out := &in.VisibilityArchivalUri, &out.VisibilityArchivalUri
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespaceParameters.
func (in *TemporalNamespaceParameters) DeepCopy() *TemporalNamespaceParameters {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespaceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespaceSpec) DeepCopyInto(out *TemporalNamespaceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespaceSpec.
func (in *TemporalNamespaceSpec) DeepCopy() *TemporalNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalNamespaceStatus) DeepCopyInto(out *TemporalNamespaceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalNamespaceStatus.
func (in *TemporalNamespaceStatus) DeepCopy() *TemporalNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(TemporalNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}
